dataset: blender
batching: single_image
factor: 2
num_coarse_samples: 96
num_fine_samples: 96
use_viewdirs: true
white_bkgd: true
batch_size: 64
randomized: true
lr_init: 5.0e-4
lr_final: 5.0e-6
lr_delay_steps: 2500
lr_delay_mult: 0.1
max_steps: 250000
save_every: 2500
render_every: 5000
print_every: 2000
gc_every: 5000
chunk: 64
net_width: 512

